### ISSUE TITLE
Only live boot is available in the ISO

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#144] opened 2017-08-07 05:19 UTC
- Issue type: Bug report 

### Short description

The ISO has two options:
- live boot 
- install the system

But both the ways start the live system even the install system also

**Comment by abishekvashok** [comment] 2017-08-19 13:01
Do we have a installer here? I don't think so.

**Comment by xeon-zolt** [comment] 2017-08-19 13:08
ubiquity is missing

**Comment by tabesin** [comment] 2017-08-22 13:06
Let's get it back then.

I guess Marios request to remove the installer was misunderstood, he meant: remove the Install entry from being displayed at the live cd desktop.

**Comment by meets2tarun** [comment] 2017-08-22 14:44
So it means that we will give the user only live boot option in the ISO? @tabesin

**Comment by abishekvashok** [comment] 2017-08-22 14:52
@meets2tarun I guess no.

> he meant: remove the Install entry from being displayed at the live cd desktop.

**Comment by meets2tarun** [comment] 2017-08-22 14:57
@abishekvashok 
I didn't get, the text is 
> remove the Install entry from being displayed at the live cd desktop.

While we boot the ISO the options appear are:
![mean](https://user-images.githubusercontent.com/15213246/29571935-4d0cedfc-8778-11e7-8329-4e464d270f8d.png)

Now tell me what to remove.

**Comment by abishekvashok** [comment] 2017-08-22 14:59
@meets2tarun see the word `desktop`; There was a install icon on the desktop as of my knowledge.

Note: There was one before GSOC

**Comment by meets2tarun** [comment] 2017-08-22 15:02
ok, I got it.
There is no install icon the desktop right now in the meilix LXQt desktop.

**Comment by tabesin** [comment] 2017-08-24 00:13
Feedback of Mario: please enable install option for live CD.

**Comment by abishekvashok** [comment] 2017-12-14 11:49
Duplicate of #185

**Comment by abishekvashok** [comment] 2017-12-24 15:00
Fixed in #221

**Comment by tabesin** [comment] 2018-03-18 14:24
Is the issue fixed?

**Comment by meets2tarun** [comment] 2018-03-18 14:26
yes, @tabesin this is fixed.
Thanks to @abishekvashok

**Closed** 2018-03-18 14:26 UTC
Labels: hacktoberfest, has-PR
